"""empty message

Revision ID: 1c92c7f6e8c6
Revises: 9881f8d680db
Create Date: 2021-01-26 00:06:12.504297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c92c7f6e8c6'
down_revision = '9881f8d680db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('accepted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'accepted')
    # ### end Alembic commands ###
