"""empty message

Revision ID: 9881f8d680db
Revises: d5cbef2a8247
Create Date: 2021-01-20 21:37:18.222718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9881f8d680db'
down_revision = 'd5cbef2a8247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.UniqueConstraint('user_id', 'sender_id', name='unique_friends')
    )
    op.create_index(op.f('ix_friends_user_id'), 'friends', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friends_user_id'), table_name='friends')
    op.drop_table('friends')
    # ### end Alembic commands ###
