"""empty message

Revision ID: d5cbef2a8247
Revises: edb7e75017b6
Create Date: 2021-01-16 19:36:54.055422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cbef2a8247'
down_revision = 'edb7e75017b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favsLists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('res_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['res_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favsLists')
    # ### end Alembic commands ###
